### ISSUE TITLE
Installed on android? Where's your spec file?

### ISSUE THREAD

**Issue by CoutinhoElias** [aniketambore/Python_Kivy_Firebase-Authentication-#1]
I am looking for a pyrebase that works after creating the application and installing it on android.

I would like to have that result.

You got it?

**Comment by anipy1** [comment]
Hello @CoutinhoElias , I spent a lot of time in the development of cross platform application with Kivy framework, but the outcome everytime is uncertain. 
My aim with Kivy is to create production ready application for android and ios . A lot of time , I tried to package it for Android but the outcome is failure.
I recommend you to go with Flutter framework, If you're aiming to build cross platform applications.

**Comment by CoutinhoElias** [comment]
I was able to read this document in full:

https://github.com/RobertFlatt/Android-for-Python/tree/main/Android-for-Python-Users#requirements
